### PR TITLE
updates deps to latest

### PR DESCRIPTION
**Pull request by justinbmeyer**

### CODE REVIEW

**Comment by phillipskevin** [comment]
@justinbmeyer doesn't this make `can-dom-events` incompatible with canjs v3? 

Currently, `canjs@3` uses these dependencies:

```
"can-dom-events": "1.0.5"
"can-globals": "0.2.6"
```

**Comment by justinbmeyer** [comment]
Does 3.0 actually use can-DOM-events?

**Comment by phillipskevin** [comment]
It definitely requires it: https://github.com/canjs/canjs/blob/3.x-legacy/can.js#L20

```
$ npm ls can-dom-events
can@3.12.1 /Users/kevin/dev/canjs
├── can-dom-events@1.0.5
├─┬ can-event-dom-enter@1.0.4
│ └── can-dom-events@1.0.5  deduped
├─┬ can-event-dom-radiochange@1.0.4
│ └── can-dom-events@1.0.5  deduped
└─┬ can-jquery@3.2.3
  └── can-dom-events@1.0.5  deduped
```

**Comment by phillipskevin** [comment]
I opened https://github.com/canjs/can-dom-events/issues/42 for this.

**Pull request merged**
